name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-infra.yml'
      - 'terraform/**'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/prod

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/prod

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/prod

      - name: Terraform Plan
        run: terraform plan -out=plan.cache
        working-directory: ./terraform/environments/prod

      - name: Save Plan and Lockfile
        uses: actions/upload-artifact@v2
        with:
          name: terraform-artifacts
          path: |
            ./terraform/environments/prod/plan.cache

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/prod

      - name: Download Plan and Lockfile
        uses: actions/download-artifact@v2
        with:
          name: terraform-artifacts
          path: ./terraform/environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.cache
        working-directory: ./terraform/environments/prod
