name: CI/CD Pipeline for Lambda

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-lambda.yml'
      - 'lambda/**'
jobs:
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda_name: [resize, crop, black-white]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ matrix.lambda_name }}:latest lambda/${{ matrix.lambda_name }} --build-arg lambda_name=${{ matrix.lambda_name }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ matrix.lambda_name }}:latest
